name: Build and Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t android-test-runner .

      # Run Tests
      - name: Run Tests
        run: |
          docker run --rm \
          -p 4723:4723 \
          -v "$(pwd)/tests:/app/tests" \
          android-test-runner bash -c "
          emulator @test_avd -no-audio -no-window -no-snapshot -accel off &
          sleep 60 &&
          ls /app/tests &&
          pytest /app/tests --maxfail=1 --disable-warnings
          "
