name: Build and Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t android-test-runner .

      # Step 3: Run the Docker container
      - name: Run Tests
        run: |
          docker run --rm -it \
          -p 4723:4723 \
          -v "$(pwd)/tests:/app/tests" \
          android-test-runner bash -c "
          emulator @test_avd -no-audio -no-window &
          adb wait-for-device &&
          sleep 20 &&
          pytest /app/tests --maxfail=1 --disable-warnings
          "
